import { Inter } from "next/font/google";
import "./globals.css";
import NavItems from "./components/NavItems";
import AuthProvider from "./context/AuthProvider";
import Footer from "./components/Footer";
// bootstrap css
import "bootstrap/dist/css/bootstrap.min.css";

// fonts and icons
import "././assets/css/icofont.min.css";
import "././assets/css/animate.css";
import "././assets/css/style.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <NavItems />
          {children}
          <Footer />
        </body>
      </AuthProvider>
    </html>
  );
}
